//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColanderToDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColanderToDriver()
        {
            this.KavimToColanders = new HashSet<KavimToColander>();
        }
    
        public int ColanderToDriverID { get; set; }
        public int TypeOfColanderID { get; set; }
        public string DriverId { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual TypeOfColander TypeOfColander { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KavimToColander> KavimToColanders { get; set; }
    }
}
