//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PreferID { get; set; }
        public string DriverId { get; set; }
        public int TypeOfColanderID { get; set; }
        public bool ExtraHour { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual TypeOfColander TypeOfColander { get; set; }
    }
}
